apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: authentication-service
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2020
        envFrom:
        - secretRef:
            name: authentication-service-secrets